### PR TITLE
Allow later versions of Microsoft.SqlServer.Types to be loaded

### PR DESCRIPTION
**Pull request by ajcvickers**
Still looks for 11 then 10 first to avoid breaking, and if not found attempts to load the most recent version from 20 down.

### CODE REVIEW

**Comment by ajcvickers** [comment]
@bricelam Sorry to randomize with EF6 stuff!

**Comment by bricelam** [comment]
When I dug into this a few months ago, I came to the conclusion that SqlClient will only work if you redirect newer versions back down 11.0.0.0...

**Comment by bricelam** [comment]
Here's [the code](https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlConnectionString.cs,412) that assumes either 10.0.0.0 or 11.0.0.0.

**Comment by ajcvickers** [comment]
@bricelam (Most) tests are passing on my machine, which after installing the latest stuff has 14 in the GAC and 14 is being loaded.

**Comment by ajcvickers** [comment]
Updated with additional test fixes. Also, updated database existence checks to remove tests that were using db_id() since it no longer sees other database when permissions to view master have been removed. This seems like an intentional change on the part of SQL Server. It doesn't break any mainline cases in EF6, and doesn't change the Azure behavior.

**Pull request merged**
