### PR TITLE
Use YAML stages

### PR DESCRIPTION
**Pull request by wtgodbe**
Resolves aspnet/AspNetCore#11924 and https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/YamlStagesPublishing.md for EFCore. @dougbu @JunTaoLuo should I port this to any of the release branches (once I have it working)?

@JohnTortugo @bricelam PTAL

I'll spin up a private internal build w/ these changes after Tactics

### CODE REVIEW

**Comment by wtgodbe** [comment]
Here's the internal build, which looks to be using stages just fine: https://dev.azure.com/dnceng/internal/_build/results?buildId=300829

**Comment by JunTaoLuo** [comment]
I think we should port these changes to preview 9 branches (release/6.3 in this repo release/3.0 in others) but not the preview 8 branches. cc @dougbu.

**Comment by JunTaoLuo** [comment]
FYI, our workflow is a little different. We make changes in release/3.0 and merge back to master. Instead of making the changes in master, cherry picking it to release/3.0 then merging it back. Can you rebase this change on release/3.0? Ditto for the other change.

**Comment by wtgodbe** [comment]
Sure, will do. To be clear, in this repo that means opening the PR in release/6.3, right?

**Comment by wtgodbe** [comment]
Closing in favor of https://github.com/aspnet/EntityFramework6/pull/1129

**Comment by dougbu** [comment]
> in this repo that means opening the PR in release/6.3, right?

right

**Pull request closed without merging**
