### PR TITLE
Add xml-docs to autogenerated migrations

### PR DESCRIPTION
**Pull request by leotsarev**
It's good (or, at least, common) practice to enable XML documentation generation. If this is enabled, auto created DbMigration's will generate warnings that pollute error logs. This change will add appropriate inheritdoc's into autogenerated code.

### CODE REVIEW

**Comment by CZEMacLeod** [comment]
@leotsarev Could you include an inheritdoc for vb.net in the vb migrations generator to keep it comparable.

**Comment by leotsarev** [comment]
@CZEMacLeod done

**Comment by ajcvickers** [comment]
@leotsarev Many tests are failing after this change. Can you please update the PR with appropriate fixes?

**Comment by leotsarev** [comment]
Yes, I'll do in ≈1-2 weeks

**Comment by davidmilligan** [comment]
Bump

**Comment by ajcvickers** [comment]
Closing due to inactivity.

**Pull request closed without merging**
