### PR TITLE
Onboard with async publishing

### PR DESCRIPTION
**Pull request by dougbu**
- repo was not included in changes documented at https://github.com/dotnet/arcade/blob/master/Documentation/NetCore3ReleasePipelinesMoveStatus.md
- see also https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing_HowToUse.md#how-do-i-use-it

### CODE REVIEW

**Comment by JohnTortugo** [comment]
Thanks @dougbu. I'll add it to the list and see if we can onboard right away.

**Comment by dougbu** [comment]
@JohnTortugo will publishing fail if we merge this change prior to something else happening?

**Comment by JohnTortugo** [comment]
To which feed should the packages be published? 

Publishing itself might not fail, but some other validation might. For instance, symbol validation. Ping me on Teams and I can help you test it before to make sure no validation will fail.

**Comment by natemcmaster** [comment]
> To which feed should the packages be published?

https://dotnetfeed.blob.core.windows.net/aspnet-entityframework6/index.json

**Comment by JohnTortugo** [comment]
@dougbu let me know if you need help validating the publishing before you merge the PR. If you push your GH branch to an AzDO branch I can give it a try.

**Comment by dougbu** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=190081 may be of interest

**Comment by dougbu** [comment]
New build attempt is https://dnceng.visualstudio.com/internal/_build/results?buildId=190401

See also aspnet/AspNetCore-Internal#2386

**Comment by dougbu** [comment]
Tests were successful (see https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=7582 as well) and this repo has already picked up the latest Arcade, including a `$(TargetStaticFeed)` setting for `"ASPNETENTITYFRAMEWORK6"`.

Many thanks to @JohnTortugo for dotnet/arcade#2771 and other assistance.

**Pull request merged**
