### PR TITLE
Remove Reverse Engineer feature from PowerTools

### PR DESCRIPTION
**Pull request by ErikEJ**
(Replaced by EF Tools and/or EF Reverse POCO Template)
see discussion here #154

### CODE REVIEW

**Comment by ErikEJ** [comment]
Ping ?

**Comment by lajones** [comment]
Checked in with commit 9891ba778.

**Comment by ErikEJ** [comment]
@lajones Any release plans? 😅

**Comment by lajones** [comment]
I'll defer to @divega :smile:

**Comment by ErikEJ** [comment]
@divega Any progress ?? 😸

**Comment by divega** [comment]
@ErikEJ getting closer to a simultaneous release with 6.2 beta, but still a few more steps to take and currently busy with Core 2.0 work.

**Comment by ErikEJ** [comment]
Thanks - mid May, I guess !!

**Comment by ErikEJ** [comment]
Any updates on ETA?

**Pull request merged**
