### PR TITLE
typo cleanup 2

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by bricelam** [comment]
@nschonni Can you squash these commits? I'm starting to think you're maliciously trying to hack your GitHub stats...

**Comment by nschonni** [comment]
There is the Squash Merge option in the UI to land it as one commit. I keep the separate because it's easier to rebase out commits if changes are requested

**Comment by bricelam** [comment]
lol, no worries. Are you editing from GitHub? I don't even know if you can rebase and squash from the web UI...

**Comment by nschonni** [comment]
> Are you editing from GitHub? I don't even know if you can rebase and squash from the web UI...

No, VS code, but I was talking about this action so you can land it as a single commit if everything looks OK https://github.blog/2016-04-01-squash-your-commits/

**Comment by ajcvickers** [comment]
Thanks!

**Comment by nschonni** [comment]
@ajcvickers did you mean to close?

**Comment by bricelam** [comment]
@nschonni Looks like it got merged via #961

**Comment by nschonni** [comment]
@bricelam that is this PR and it was closed without merging

**Comment by nschonni** [comment]
Oh, I see #977

**Comment by nschonni** [comment]
Looks like a branch was created with all but the first commit from the PR

**Pull request closed without merging**
