### PR TITLE
Ingest latest core-setup and target .NET 5

### PR DESCRIPTION
**Pull request by nguerrera**
@dougbu @JunTaoLuo @ajcvickers

### CODE REVIEW

**Comment by nguerrera** [comment]
Subsumes #1109

**Comment by ajcvickers** [comment]
@bricelam Can you take a look at this?

**Comment by ajcvickers** [comment]
@bricelam Probably. Do we need another branch here?

**Comment by bricelam** [comment]
No, we should just bump master to 6.5. We'll create a 6.3 branch when we create the other 3.1 branches

**Comment by nguerrera** [comment]
FYI, I've started getting the 5.0 sdk builds into shape. You won't need the two workarounds, once you can update to and SDK with this: https://github.com/dotnet/core-sdk/pull/3741

**Comment by dougbu** [comment]
@nguerrera due to source build restrictions, we need to stick with a released SDK

**Pull request merged**
