### PR TITLE
Trs79 master

### PR DESCRIPTION
**Pull request by ajcvickers**
Rebased PR

### CODE REVIEW

**Comment by bricelam** [comment]
@ajcvickers You can force-push to other people's PRs to avoid creating new ones.

**Comment by ajcvickers** [comment]
@bricelam Tried that, but couldn't make it work.

**Comment by bricelam** [comment]
Ah, users have the option to disable it. It was also disabled for any PRs opened before the feature was added.

**Comment by ajcvickers** [comment]
Or I was just doing it wrong...

**Pull request merged**
