### PR TITLE
PowerTools: Upgrade to a v2 vsixmanifest

### PR DESCRIPTION
**Pull request by bricelam**
This drops support for VS 2010, but adds support for VS 2017 and future releases (in theory).

cc @divega @rowanmiller

### CODE REVIEW

**Comment by bricelam** [comment]
Hmm...
image

**Comment by bricelam** [comment]
It doesn't appear to be working in VS 2017 RC. This PR may not be worth taking.

**Comment by lajones** [comment]
Agreed. See the email I just sent round about why this won't work for VS15 (basically we will need VSIX V3 for that) - so I think we should take the other approach for now.

**Comment by bricelam** [comment]
Recalling.

**Pull request closed without merging**
