### PR TITLE
Update SDK

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Copy of https://github.com/aspnet/Blazor/pull/1929

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
Hmm looks like the SDK broke something for this repo.

**Comment by JunTaoLuo** [comment]
The symptoms look like https://github.com/microsoft/msbuild/issues/4695 but given that it's been marked as fixed, I'm not sure how it's showing up in 5.0 SDK @rainersigwald ?

**Comment by rainersigwald** [comment]
The SDK you're updating to is built off https://github.com/microsoft/msbuild/commit/e460c009a8fc6db1e3a40ec17d380dfd09344e1e, which didn't yet have the fix (which was committed late in 16.3 after we forked, so the early 16.4 MSBuilds didn't have it).

The very latest 5.0 SDKs should have newer MSBuilds with the fix; can you update to newer @JunTaoLuo?

There was a little while when MSBuild wasn't flowing to 5.0 because Arcade doesn't support publishing to two channels, but that should be resolved for now.

**Comment by JunTaoLuo** [comment]
Ah I see, let me try a new SDK then.

**Comment by wtgodbe** [comment]
Curious to see if you hit the same test failure as in https://github.com/aspnet/EntityFramework6/pull/1291

**Comment by JunTaoLuo** [comment]
Yup same failures:
```
System.Resources.MissingManifestResourceException : Could not find the resource \"System.Data.Entity.Properties.Resources.resources\" among the resources \"System.Data.Entity.Resources.Strings.resources\", \"System.Data.Resources.AnnotationSchema.xsd\", \"System.Data.Resources.CodeGenerationSchema.xsd\", \"System.Data.Resources.CSDLSchema_1.xsd\", \"System.Data.Resources.CSDLSchema_1_1.xsd\", \"System.Data.Resources.CSDLSchema_2.xsd\", \"System.Data.Resources.CSDLSchema_3.xsd\", \"System.Data.Resources.EntityStoreSchemaGenerator.xsd\", \"System.Data.Resources.SSDLSchema.xsd\", \"System.Data.Resources.SSDLSchema_2.xsd\", ... embedded in the assembly \"EntityFramework\", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
```

**Comment by JunTaoLuo** [comment]
@ajcvickers Can someone from your team help take a look at the latest test failures?

**Comment by JunTaoLuo** [comment]
Same test failures encountered in https://github.com/aspnet/EntityFramework6/pull/1291 @bricelam

**Comment by JunTaoLuo** [comment]
FYI @sebastienros

**Comment by dougbu** [comment]
@bricelam any suggestions?

@JunTaoLuo you'll probably need to add my aspnet/EntityFrameworkCore#18847 changes to get official builds working end-to-end. Might be fastest to do that all together (once you fix the test issue).

**Comment by JunTaoLuo** [comment]
I updated with @bricelam's fix in https://github.com/aspnet/EntityFramework6/pull/1291

**Comment by JunTaoLuo** [comment]
Ah I was planning on fixing that in a separate PR since I the disabling of the signing validation is temporary whereas this is a permanent fix. But I suppose I can keep them as separate commits but use the same PR. Will update.

**Comment by dougbu** [comment]
Thanks @JunTaoLuo

**Pull request merged**
