### PR TITLE
Update SDK to preview 7

### PR DESCRIPTION
**Pull request by JunTaoLuo**
Addresses aspnet/AspNetCore-Internal#2774

### CODE REVIEW

**Comment by bricelam** [comment]
(Still wondering why we have to do this manually...)

**Comment by dougbu** [comment]
@bricelam because the SDK doesn't exist in a Maestro++ channel and Arcade's minimum SDK lags, then lags some more.

**Comment by bricelam** [comment]
Should we re-open dotnet/arcade#811? (or at least file a new issue)

**Comment by dougbu** [comment]
The flow from Arcade works. The problem I was talking about was just them updating the SDK reactively i.e. when someone mentions it's lagging. Then, they need to notify Arcade users and wait a bit before changing. We generally want to move faster.

That said, I could open another Arcade PR to start their process. Is that important at this point?

**Comment by bricelam** [comment]
I’m fine with it as it is (since I’m not the one doing it) it just feels like arcade didn’t deliver the feature we asked for

**Comment by bricelam** [comment]
I.e. we should be able to opt into the latest SDK, not a “minimum required” version

**Pull request merged**
