### PR TITLE
[release/6.3] PMC define web startup project directory

### LINKED ISSUE #1290: EF 6.3.0 PMC commands throw `ParameterBindingValidationException` when Startup Project is a Web App
This issue is meant to provide more light on #492 and offer a solution. I made a more detailed explanation and proposed mitigation there, but I will copy my comment here:

> I realize that this issue is closed but I too have started seeing this issue and thought this might be helpful still.
> 
> Here's my solution set up:
> 
> * .NET Framework 4.7.2 Web App (here called `Project`)
> * I have placed my Models, Migrations, and DbContext in a separate project `Project.Data`
> 
> My repro steps are:
> 
> 1. Start by using EF 6.2.0
> 2. `Update-Package EntityFramework` to use 6.3.0
> 3. Run `Add-Migration ANewMigration`
> 4. Receive:
> 
> ```powershell
> Add-Migration : Cannot bind argument to parameter 'Path' because it is null.
> At line:1 char:1
> + Add-Migration -StartUpProjectName Pegasus -ProjectName Pegasus.Data - ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Add-Migration], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Add-Migration
> ```
> 
> I debugged the NuGet package locally and found that this was consistently happening on each of the PMC commands.
> 
> Furthermore, I found that this `ParameterBindingValidationException` is happening here:
> 
> ```powershell
>     if (IsWeb $startupProject)
>     {
>         $params += '--data-dir', (Join-Path $startupProjectDir 'App_Data')
>     }
> ```
> 
> on [line 918 of src/NuGet/EntityFramework/tools/EntityFramework6.psm1](https://github.com/aspnet/EntityFramework6/blob/7d7d5fe22240bebaae76352828165822aa99940a/src/NuGet/EntityFramework/tools/EntityFramework6.psm1#L916-L919)
> 
> I noticed that `$startupProjectDir` is the path for `Join-Path` but it is not defined at any place in the PMC for that version.
> 
> Locally, I was able to resolve this by updating these lines like this:
> 
> ```powershell
>     if (IsWeb $startupProject)
>     {                
>         $startupProjectDir = GetProperty $startupProject.Properties 'FullPath'        
>         $params += '--data-dir', (Join-Path $startupProjectDir 'App_Data')
>     }
> ```
> 
> This allowed me to use the PMC from an external project. I hope this helps!
> 
> P.S. I started a new .NET Framework 4.7.2 web app, with Models and DbContext in the same project and installed EF 6.3.0 right off and still received the same error.
> 
> I'd be happy to submit a PR for this if you guys are up for it. Just let me know!

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #1290

cc @Pilchie

### CODE REVIEW

**Comment by bricelam** [comment]
(Wrong branch. Will change once GitHub UI stops glitching)

**Comment by Pilchie** [comment]
Go ahead and merge when CI passes.

**Comment by bricelam** [comment]
@AndriySvyryd Did we do anything on this repo to fix this issue?

> Unable to open the physical file "F:\workspace.7\_work\1\s\bin\AnyCPU.Debug-netcoreapp3_0\Microsoft.ML.Tests\netcoreapp3.0\TestDatabases\iris.mdf". Operating system error 3: "3(The system cannot find the path specified.)".
> File activation failure. The physical file name "F:\workspace.7\_work\1\s\bin\AnyCPU.Debug-netcoreapp3_0\Microsoft.ML.Tests\netcoreapp3.0\TestDatabases\iris_log.ldf" may be incorrect.

...we might need to cherry-pick it into release/6.3

**Comment by AndriySvyryd** [comment]
@bricelam You can go ahead and cherry-pick https://github.com/aspnet/EntityFramework6/commit/ea8ded0aea6aa90c411cea3cecf71a1b2f90a926
I'm going on vacation and won't be able to do it today

**Pull request merged**
