### PR TITLE
Nullable Keys are now being allowed.

### PR DESCRIPTION
**Pull request by lajones**
Fix for #243. Previously we disallowed nullable key properties. This fix allows them.

### CODE REVIEW

**Comment by divega** [comment]
I am surprised that it was enough to remove the validation rule. Don't we also have to change some code to always set key members as non-nullable when we are processing the schema discovery queries?

**Comment by lajones** [comment]
@divega That sounds contrary to the approach I thought @ajcvickers was suggesting. I thought the approach was to allow things to be nullable where possible (knowing that that might cause problems at runtime if there actually is a null in the DB). See [this comment](https://github.com/aspnet/EntityFramework6/issues/243#issuecomment-294220463).

However that comment does also mention a warning from the scaffolding tool - I should add that. But I'd like to get this in so I can "re-freeze" the runtime.

**Comment by divega** [comment]
@lajones I think I understand how you read that comment, however it clearly says we need to change the designer :smile:

**Comment by ajcvickers** [comment]
@lajones I'm sorry my comment was not clear enough. Let me try to be more specific.

The problem, as I understand it, is:
* Nullable columns are allowed for primary keys in some database engines
* If a column in a key comes back as nullable, then some piece of the reverse engineering code says that that is invalid because EF6 doesn't allow nullable key properties
* However, if the user was not using reverse engineering and setup their model using non-nullable properties*, then EF6 would not complain (as long as there aren't actually any null key values).

Therefore the solution we want to get to is for reverse engineering to generate the model that could have been setup by hand using non-nullable properties*. (Ideally it should generate a warning when doing this indicating that the nullability of the key columns is being ignored and that if there are null keys values, then this will not work at runtime because EF doesn't support null key values. But I could live without the warning if this is a lot of work.)

So, my comment was meant to convey that the gist of all this is to stop rejecting the columns/keys in reverse engineering _and then also ensure that the generated model actually works_, doing whatever property coercion is needed, etc. Sorry I wasn't clear about this. 

* When I say non-nullable properties, I'm not sure if the CLR type needs to be non-nullable, if the c-space type needs to be non-nullable, or if only the s-space type needs to be non-nullable. This is something that I would expect you to determine as part of the fix--probably just by editing an EDMX to see what happens in the different cases. Beyond that, even if the CLR types and/or the c-space type can nullable, given that null values are not allowed I would probably err on the side of making the property non-nullable at all levels, since I think that better matches the semantics of what is happening, and null doesn't have special meaning like it does in EF Core. But hopefully you can look at the code, try a few things, and make a recommendation on this. Probably also worth asking @divega's opinion.

**Comment by divega** [comment]
@lajones @ajcvickers my mental model of how it currently works is mostly the same:

1. Reverse engineering executes a schema discovery query and gets back a table with columns and key metadata. For whatever reason (possibly a limitation of the provider, the database or the schema discovery queries) the metadata about the keys specifies that they are nullable S-space types. 
2. Reverse engineering constructs a model with the table/column/key metadata it obtained. While doing so it reflects the fact that the keys are reported as nullable into the model.
3. Then the  pass this to the model through semantic validation. The validation rule from the runtime throws because EF does not accept nullable key members. 

Here is what I think we want to happen after the fix:

1. Reverse engineering executes a schema discovery query and gets back a table with columns and key metadata. For whatever reason (possibly a limitation of the provider, the database or the schema discovery queries) the metadata about the keys specifies that they are nullable S-space types. 
2. Reverse engineering constructs a model with the table/column/key metadata it obtained. While doing so it **ignores the fact that the keys are reported as nullable** and makes them always non-nullable in the model.
3. Then the  pass this to the model through semantic validation. The validation rule from the runtime **passes** because all keys are non-nullable. 

I agree with @ajcvickers that a warning would be nice if in step (2) we find that the keys were reported as nullable, but I believe it is very low priority in my mind because the likelihood of a relational database reporting that PKs are nullable because they are really nullable is extremely low.

**Comment by lajones** [comment]
Closing this PR as it doesn't address the issue the way that was meant. Will open a new PR addressing this in the designer.

**Pull request closed without merging**
